mysite/ads/urls.py
from django.urls import path, reverse_lazy
from . import views

app_name = 'ads'
urlpatterns = [
    path('', views.AdListView.as_view()),
    path('ads', views.AdListView.as_view(), name='all'),
    path('ad/<int:pk>', views.AdDetailView.as_view(), name='ad_detail'),
    path('ad/create',
         views.AdCreateView.as_view(success_url=reverse_lazy('ads:all')), name='ad_create'),
    path('ad/<int:pk>/update',
         views.AdUpdateView.as_view(success_url=reverse_lazy('ads:all')), name='ad_update'),
    path('ad/<int:pk>/delete',
         views.AdDeleteView.as_view(success_url=reverse_lazy('ads:all')), name='ad_delete'),
    path('ad_picture/<int:pk>', views.stream_file, name='ad_picture'),
    path('ad/<int:pk>/comment',
         views.CommentCreateView.as_view(), name='ad_comment_create'),
    path('comment/<int:pk>/delete',
         views.CommentDeleteView.as_view(success_url=reverse_lazy('ads')), name='ad_comment_delete'),
]

mysite/mysite/urls.py
import os
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.views.static import serve

urlpatterns = [
    path('', include('home.urls')),  # Change to ads.urls
    path('admin/', admin.site.urls),  # Keep
    path('accounts/', include('django.contrib.auth.urls')),  # Keep
    url(r'^oauth/', include('social_django.urls', namespace='social')),  # Keep
    path('ads/', include('ads.urls')),
]

# Serve the static HTML
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
urlpatterns += [
    url(r'^site/(?P<path>.*)$', serve,
        {'document_root': os.path.join(BASE_DIR, 'site'),
         'show_indexes': True},
        name='site_path'
        ),
]

# Serve the favicon - Keep for later
urlpatterns += [
    path('favicon.ico', serve, {
            'path': 'favicon.ico',
            'document_root': os.path.join(BASE_DIR, 'home/static'),
        }
    ),
]

# Switch to social login if it is configured - Keep for later
try:
    from . import github_settings
    social_login = 'registration/login_social.html'
    urlpatterns.insert(0,
                       path('accounts/login/', auth_views.LoginView.as_view(template_name=social_login))
                       )
    print('Using', social_login, 'as the login template')
except:
    print('Using registration/login.html as the login template')

# References

# https://docs.djangoproject.com/en/3.0/ref/urls/#include

mysite/ads/models.py
from django.db import models
from django.core.validators import MinLengthValidator
from django.contrib.auth.models import User
from django.conf import settings


class Comment(models.Model):
    text = models.TextField(
        validators=[MinLengthValidator(3, 'Comment must be greater than 3 characters')]
    )
    ad = models.ForeignKey('Ad', on_delete=models.CASCADE)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        if len(self.text) < 15: return self.text
        return self.text[:11] + ' ...'


class Ad(models.Model):
    title = models.CharField(
        max_length=200,
        validators=[MinLengthValidator(2, "Title must be greater than 2 characters")]
    )
    price = models.DecimalField(max_digits=7, decimal_places=2, null=True)
    text = models.TextField()
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    comments = models.ManyToManyField(settings.AUTH_USER_MODEL, through=Comment, related_name='comments_ownder')

    # Picture
    picture = models.BinaryField(null=True, editable=True)
    content_type = models.CharField(max_length=256, null=True, help_text='The MIMEType of this file')

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    # Shows up in the admin list
    def __str__(self):
        return self.title

mysite/ads/forms.py
from django import forms
from .models import Ad

from django.core.files.uploadedfile import InMemoryUploadedFile
from .humanize import naturalsize


class CreateForm(forms.ModelForm):
    max_upload_limit = 2 * 1024 * 1024
    max_upload_limit_text = naturalsize(max_upload_limit)

    picture = forms.FileField(required=False, label=f'File to upload <= {max_upload_limit_text}')
    upload_field_name = 'picture'

    class Meta:
        model = Ad
        fields = ['title', 'price', 'text', 'picture']

    def clean(self):
        cleaned_data = super().clean()
        pic = cleaned_data.get('picture')
        if pic is None:
            return
        if len(pic) > self.max_upload_limit:
            self.add_error('picture', f'File must be < {self.max_upload_limit_text} bytes')

    def save(self, commit=True):
        instance = super().save(commit=False)
        f = instance.picture
        if isinstance(f, InMemoryUploadedFile):
            bytearr = f.read()
            instance.content_type = f.content_type
            instance.picture = bytearr

        if commit:
            instance.save()

        return instance


# strip means to remove whitespace from the beginning and the end before storing the column
class CommentForm(forms.Form):
    comment = forms.CharField(required=True, max_length=500, min_length=3, strip=True)

mysite/ads/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.views import View
from .owner import *

from .models import Ad, Comment

from .forms import CreateForm, CommentForm


# Create your views here.


class AdListView(OwnerListView):
    model = Ad


class AdDetailView(OwnerDetailView):
    model = Ad
    template_name = 'ads/ad_detail.html'

    def get(self, request, *args, **kwargs):
        ad = get_object_or_404(Ad, id=kwargs.get('pk'))
        comments = Comment.objects.filter(ad=ad).order_by('-updated_at')
        comment_form = CommentForm()
        ctx = {
            'ad': ad,
            'comments': comments,
            'comment_form': comment_form
        }
        return render(request, self.template_name, ctx)


class AdCreateView(LoginRequiredMixin, View):
    template_name = 'ads/ad_form.html'
    success_url = reverse_lazy('ads:all')

    def get(self, request, *args, **kwargs):
        form = CreateForm()
        ctx = {'form': form}
        return render(request, self.template_name, ctx)

    def post(self, request, *args, **kwargs):
        form = CreateForm(request.POST, request.FILES or None)

        if not form.is_valid():
            ctx = {'form': form}
            return render(request, self.template_name, ctx)

        ad = form.save(commit=False)
        ad.owner = self.request.user
        ad.save()
        return redirect(self.success_url)


class AdUpdateView(LoginRequiredMixin, View):
    template_name = 'ads/ad_form.html'
    success_url = reverse_lazy('ads:all')

    def get(self, request, *args, **kwargs):
        ad = get_object_or_404(Ad, pk=kwargs.get('pk'))
        form = CreateForm(instance=ad)
        ctx = {'form': form}
        return render(request, self.template_name, ctx)

    def post(self, request, *args, **kwargs):
        ad = get_object_or_404(Ad, pk=kwargs.get('pk'))
        form = CreateForm(request.POST, request.FILES or None, instance=ad)

        if not form.is_valid():
            ctx = {'form': form}
            return render(request, self.template_name, ctx)

        form.save()
        return redirect(self.success_url)


class AdDeleteView(OwnerDeleteView):
    model = Ad


def stream_file(request, pk):
    ad = get_object_or_404(Ad, id=pk)
    response = HttpResponse()
    response['Content-Type'] = ad.content_type
    response['Content-Length'] = len(ad.picture)
    response.write(ad.picture)
    return response


class CommentCreateView(LoginRequiredMixin, View):

    def post(self, request, *args, **kwargs):
        f = get_object_or_404(Ad, id=kwargs.get('pk'))
        comment = Comment(text=request.POST['comment'], owner=request.user, ad=f)
        comment.save()
        return redirect(reverse('ads:ad_detail', args=[kwargs.get('pk')]))


class CommentDeleteView(OwnerDeleteView):
    model = Comment
    template_name = 'ads/comment_delete.html'

    def get_success_url(self):
        ad = self.object.ad
        return reverse('ads:ad_detail', args=[ad.id])

mysite/ads/templates/ads/ad_confirm_delete.html
{% extends "base_menu.html" %}
{% block content %}
<h1>Delete Article</h1>

<p>Are you sure you want to delete the ad: {{ ad }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>
{% endblock %}

mysite/ads/templates/ads/ad_detail.html
{#{% extends "base_menu.html" %}#}
{#{% load humanize %} <!-- https://docs.djangoproject.com/en/3.0/ref/contrib/humanize -->#}
{#{% block content %}#}
{#    <span style="float: right;">#}
{#({{ ad.updated_at|naturaltime }})#}
{#        {% if ad.owner == user %}#}
{#            <a href="{% url 'ads:ad_update' ad.id %}"><i class="fa fa-pencil"></i></a>#}
{#            <a href="{% url 'ads:ad_delete' ad.id %}"><i class="fa fa-trash"></i></a>#}
{#        {% endif %}#}
{#</span>#}
{#    <h1>{{ ad.title }}</h1>#}
{#    <p>#}
{#        {{ ad.text }}#}
{#    </p>#}
{#    <p>#}
{#    </p>#}
{#    <p>#}
{#        <a href="{% url 'ads:all' %}">All Ads</a>#}
{#    </p>#}
{#{% endblock %}#}


{% extends "base_menu.html" %}
{% load crispy_forms_tags %}
{% load humanize %} <!-- https://docs.djangoproject.com/en/3.0/ref/contrib/humanize -->
{% block head %}
    <style>
        .overlay {
            position: fixed;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            z-index: 10;
            display: none;
            background-color: rgba(0, 0, 0, 0.5); /*dim the background*/
        }
    </style>
{% endblock %}
{% block content %}
    {% if ad.content_type %}
        <div id="overlay" class="overlay" style="text-align: center;"
             onclick="document.getElementById('overlay').style.display = 'none';">
            <img style="width:90%;margin-top: 50px; border:3px solid black;" src="{% url 'ads:ad_picture' ad.id %}">
        </div>
    {% endif %}
    <span style="float: right;">
({{ ad.updated_at|naturaltime }})
        {% if ad.owner == user %}
            <a href="{% url 'ads:ad_update' ad.id %}"><i class="fa fa-pencil"></i></a>
            <a href="{% url 'ads:ad_delete' ad.id %}"><i class="fa fa-trash"></i></a>
        {% endif %}
</span>
    <h1>{{ ad.title }}</h1>
    {% if ad.content_type %}
        <img style="float:right; max-width:50%;" src="{% url 'ads:ad_picture' ad.id %}"
             onclick="document.getElementById('overlay').style.display = 'block';">
    {% endif %}
    <p>
        {{ ad.text }}
    </p>
    <p>
        Price: ${{ ad.price }}
    </p>

    {% if user.is_authenticated %}
        <form action="{% url 'ads:ad_comment_create' ad.id %}" method="POST">
            {% csrf_token %}
            {{ comment_form|crispy }}
            <input type="submit" value="Submit">
            <input type="submit" value="All Ads" onclick="window.location.href='{% url 'ads:all' %}';return false;">
        </form>
    {% endif %}
    <br>

    {% for comment in comments %}
        <p>{{ comment.text }}
        ({{ comment.updated_at|naturaltime }})
        {% if user == comment.owner %}
            <a href="{% url 'ads:ad_comment_delete' comment.id %}"><i class="fa fa-trash"></i></a>
            </p>
        {% endif %}
    {% endfor %}
    <a href="{% url 'ads:all' %}">All pics</a>

{% endblock %}

mysite/ads/templates/ads/ad_form.html
{% extends "base_menu.html" %}
{% load crispy_forms_tags %}
{% block content %}
<p>
  <form action="" method="post" id="upload_form" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Submit">
    <input type="submit" value="Cancel" onclick="window.location.href='{% url 'ads:all' %}';return false;">
  </form>
</p>
    <!-- https://stackoverflow.com/questions/2472422/django-file-upload-size-limit -->
<script>
$("#upload_form").submit(function() {
  console.log('Checking file size');
  if (window.File && window.FileReader && window.FileList && window.Blob) {
      var file = $('#id_{{ form.upload_field_name }}')[0].files[0];
      if (file && file.size > {{ form.max_upload_limit }} ) {
          alert("File " + file.name + " of type " + file.type + " must be < {{ form.max_upload_limit_text }}");
      return false;
    }
  }
});
</script>
{% endblock %}

mysite/ads/templates/ads/ad_list.html
{% extends "base_menu.html" %}
{% block content %}
    <h1>Ads</h1>
    <p>
        {% if ad_list %}
            <ul>
                {% for ad in ad_list %}
                    <li>
                        <a href="{% url 'ads:ad_detail'  ad.id %}">{{ ad.title }}</a>
                        {% if ad.owner == user %}
                            (<a href="{% url 'ads:ad_update' ad.id %}">Edit</a> |
                            <a href="{% url 'ads:ad_delete' ad.id %}">Delete</a>)
                        {% endif %}
                    </li>
                {% endfor %}
            </ul>
        {% else %}
            <p>There are no ads in the database.</p>
        {% endif %}
    </p>
    <p>
        <a href="{% url 'ads:ad_create' %}">Add an Ad</a> |
        {% if user.is_authenticated %}
            <a href="{% url 'logout' %}?next={% url 'ads:all' %}">Logout</a>
        {% else %}
            <a href="{% url 'login' %}?next={% url 'ads:all' %}">Login</a>
        {% endif %}
    </p>
{% endblock %}

mysite/ads/templates/ads/comment_delete.html
{% extends "base_menu.html" %}
{% block content %}
<h1>Delete Comment</h1>

<p>Are you sure you want to delete</p>
<p>{{ comment.text }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit"  class="btn btn-primary" value="Yes, delete.">
  <a href="{% url 'ads:ad_detail' comment.ad.id %}" class="btn btn-secondary">Cancel</a>
</form>
{% endblock %}